USE pizzatowndha;

CREATE TABLE Units (
    Id VARCHAR(36) PRIMARY KEY NOT NULL,
    UnitSymbol VARCHAR(20) NOT NULL,
    UnitName VARCHAR(50) NOT NULL UNIQUE,
    Category VARCHAR(30) NOT NULL,
    IsBaseUnit TINYINT NOT NULL DEFAULT 0,
    ConversionFactor DECIMAL(20,10) NOT NULL,
    DisplayOrder INT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50) DEFAULT NULL,
    UpdatedAt DATETIME DEFAULT NULL,
    IsDeleted TINYINT DEFAULT 0
);


CREATE TABLE ingredients (
    Id VARCHAR(36) NOT NULL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    UnitId VARCHAR(36) NOT NULL,
    PhysicalStock DECIMAL(18, 4) NOT NULL DEFAULT 0.0000,
    MinimumStock DECIMAL(18, 4) NOT NULL DEFAULT 0.0000,
    Tolerance DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
    CreatedBy VARCHAR(100) NOT NULL DEFAULT 'System',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(100) NULL,
    UpdatedAt DATETIME NULL
);

CREATE TABLE products (
    Id VARCHAR(36) NOT NULL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedBy VARCHAR(100) NOT NULL DEFAULT 'System',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(100) NULL,
    UpdatedAt DATETIME NULL
);

CREATE TABLE product_ingredients (
    Id VARCHAR(36) NOT NULL PRIMARY KEY,
    ProductId VARCHAR(36) NOT NULL,
    IngredientId VARCHAR(36) NOT NULL,
    QuantityRequired DECIMAL(18, 4) NOT NULL DEFAULT 1.0000
);

CREATE TABLE kitchen_logs (
    Id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    ProductId CHAR(36) NOT NULL,
    QuantityMade INT NOT NULL DEFAULT 1,
    DateLogged DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stock_audits (
    Id VARCHAR(36) NOT NULL PRIMARY KEY,
    IngredientId VARCHAR(36) NOT NULL,
    OpeningStock DECIMAL(18,4) NOT NULL DEFAULT 0,
    ActualClosingStock DECIMAL(18,4) NOT NULL DEFAULT 0,
    AuditDate DATE NOT NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedBy VARCHAR(100) DEFAULT 'System',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL
);

CREATE TABLE stock_ins (
    Id VARCHAR(36) NOT NULL PRIMARY KEY,
    IngredientId VARCHAR(36) NOT NULL,
    QuantityReceived DECIMAL(18,4) NOT NULL DEFAULT 0,
    ReceivedDate DATE NOT NULL,
    Notes VARCHAR(255) NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedBy VARCHAR(100) DEFAULT 'System',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL
);

